# Generated by Django 5.1.7 on 2025-03-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='team_description',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='milestones',
            field=models.TextField(blank=True, default='2018: Launched our first school.\n2020: Organized 100+ health camps in rural areas.\n2022: Reached the milestone of 10,000 beneficiaries.'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='App.aboutus')),
            ],
        ),
    ]
