# Generated by Django 5.1.7 on 2025-03-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_aboutus_team_description_aboutus_milestones_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisionMission',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='mission_description',
            field=models.TextField(blank=True, default='To provide quality education to every child, regardless of their socio-economic background.'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='mission_title',
            field=models.CharField(blank=True, default='Our Mission', max_length=150),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='vision_description',
            field=models.TextField(blank=True, default='A world where every individual has the opportunity to live with dignity and purpose.'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='vision_title',
            field=models.CharField(blank=True, default='Our Vision', max_length=150),
        ),
    ]
