# Generated by Django 5.1.7 on 2025-03-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_delete_visionmission_aboutus_mission_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vision_title', models.CharField(max_length=150)),
                ('vision_description', models.CharField(max_length=200)),
                ('mission_title', models.CharField(max_length=150)),
                ('mission_description', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
