# Generated by Django 5.1.7 on 2025-03-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_remove_project_image_url_remove_project_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
