# Generated by Django 5.1.7 on 2025-03-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_project_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('upcoming', 'Upcoming'), ('active', 'Active')], default='ongoing', max_length=20),
        ),
    ]
