# Generated by Django 5.1.7 on 2025-03-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
